### ISSUE TITLE
Change float to int in Player class

### ISSUE THREAD

**Issue by abbygriffiths** [dwillis/python-espncricinfo#11]
Creating a Player object leads to a problem in the _batting_fielding_averages method, on line 84, with num_formats using the / operator, which gives a float instead of the // operator to get an int. This raises an error when it is used to create a range on line 85.

**Comment by dwillis** [comment]
@abbygriffiths Hi, thanks for the report. Is this still an issue for you, and are you using Python 2 or 3?
