### ISSUE TITLE
Trying to convert NoneType to Float isn't handeled

### ISSUE THREAD

**Issue by Ehsan1997** [dwillis/python-espncricinfo#15]
I found error on a match that had no result, and the match ended without the second team playing a ball. So I opened match.py, and found out float conversion can cause the script to fail if there is NoneType returned. Please use exception handling or whatever you deem fit.

**Comment by dwillis** [comment]
@Ehsan1997 Thanks for this report.

**Comment by dwillis** [comment]
@Ehsan1997 can you give me the specific match for this report?

**Comment by Ehsan1997** [comment]
There where 2 PSL matches. You can try any matches which did not end with a result and the second team did not bat.

**Comment by Ehsan1997** [comment]
There were*

**Comment by Ehsan1997** [comment]
Here's the link.
http://www.espncricinfo.com/series/8679/scorecard/1128828/multan-sultans-vs-karachi-kings-11th-match/

**Comment by dwillis** [comment]
@Ehsan1997 sorry it has taken so long, but I just pushed a fix for this.
