### ISSUE TITLE
match.toss_decision returns null

### ISSUE THREAD

**Issue by Ehsan1997** [dwillis/python-espncricinfo#17]
Is it just me or the toss_decision attribute is returning a null string.

**Comment by Ehsan1997** [comment]
Okay, the toss_decision attribute in official cricinfo json is an empty string.

**Comment by dwillis** [comment]
@Ehsan1997 Good catch, yes. That rule should apply with the exception of some first-class matches in England's county championship, which now has the option of having no toss.
