### ISSUE TITLE
[FeatureRequest] Getting all the ids of the match belonging to a specific series or league (e.g. PSL, IPL)

### ISSUE THREAD

**Issue by Ehsan1997** [dwillis/python-espncricinfo#19]

**Comment by dwillis** [comment]
@Ehsan1997 I've added several methods to `Series`, including `get_events_for_season`. Details at https://github.com/dwillis/python-espncricinfo/commit/4fafee3e333990e1b8d5d6c9ed0adcdf29f3d83b.
