### ISSUE TITLE
Convert List of Dictionaries to a Single Dictionary

### ISSUE THREAD

**Issue by Ehsan1997** [dwillis/python-espncricinfo#25]
While trying to access the batting_fielding_averages of a player we get a list of Dictionaries (With just one key, value pair) which is very annoying, because it forces you to do this:
`player.batting_fielding_averages[2]['T20Is]` rather than `player.batting_fielding_averages['T20Is]`. I can fix this in places where I observe this, but until all such issue are solved this issue should remain open.

**Comment by dwillis** [comment]
Just pushed a fix for this that also changes the interior tuples into a dict, so you can now use syntax like this: `p.batting_fielding_averages['Tests']['high_score']`
