### ISSUE TITLE
A few Player Ids whose Object creation fails

### ISSUE THREAD

**Issue by Ehsan1997** [dwillis/python-espncricinfo#27]
['874261', '878035', '749957', '858807', '515870', '743645', '515904', '878055', '743647', '580662', '646213', '878025', '885815', '517573', '874173', '1008089']

Above mentioned is the list of ids of player whose object creation fails.

My guess is the problem is in the constructor when Bowling averages are being parsed.

**Comment by scrambldchannel** [comment]
I know this is from a while back but I cam across it too and worked on a fix. I'll pull together a PR
