### ISSUE TITLE
'method' object is not subscriptable

### ISSUE THREAD

**Issue by MahmudulHassan5809** [dwillis/python-espncricinfo#36]
**Describe the bug**
Try to get summary of live matches, by crating  an instance of the Summary class get this error 
**TypeError: 'method' object is not subscriptable**

**Here is My Code **
```
    s = Summary()
    print(s.match_ids)
```
**Here is the error**
![image](https://user-images.githubusercontent.com/35035594/85205879-03211500-b340-11ea-980e-8c8a8ffff2df.png)

**Comment by dwillis** [comment]
@MahmudulHassan5809 Thanks for this - it should be fixed now.

**Comment by MahmudulHassan5809** [comment]
Hello Thanks for soling the problem but now it gives me this error **'NoneType' object is not iterable**

Here is my code 

```
def cricket_live(request):
    s = Summary()
```
**Here is The Error**
![image](https://user-images.githubusercontent.com/35035594/85844539-b5376180-b7c4-11ea-9e0f-a30091f46478.png)

**Comment by MahmudulHassan5809** [comment]
Thanks Its Working Now.
