### ISSUE TITLE
Espn website used for JSON object not available

### ISSUE THREAD

**Issue by pranaykarwa** [dwillis/python-espncricinfo#38]
Hi! Amazing work with this project. Although I haven't quite understood how to use it entirely, I tried to read through the code, and found this in 'player.py'

`self.json_url = "https://core.espnuk.org/v2/sports/cricket/athletes/{0}".format(str(player_id))`

This URL isn't available anymore it seems.  Would you happen to know any alternate websites or sources where we could get player data packaged in a JSON?

**Comment by dwillis** [comment]
@pranaykarwa Thanks! Sadly I have not found an alternative and will be removing `json_url` from the Player objects.

**Comment by prasanna-sk** [comment]
> Hi! Amazing work with this project. Although I haven't quite understood how to use it entirely, I tried to read through the code, and found this in 'player.py'
> 
> `self.json_url = "https://core.espnuk.org/v2/sports/cricket/athletes/{0}".format(str(player_id))`
> 
> This URL isn't available anymore it seems. Would you happen to know any alternate websites or sources where we could get player data packaged in a JSON?

Just change the https to http. It looks like https has been removed for quite a few of the links. 
e.g. below works
http://core.espnuk.org/v2/sports/cricket/athletes/447261

**Comment by dwillis** [comment]
@prasanna-sk @pranaykarwa thank you - have pushed this change.
