### ISSUE TITLE
Improve Match API

### ISSUE THREAD

**Issue by xaranke** [dwillis/python-espncricinfo#6]
1) I don't think you should pass in an int, you should pass in a string so that you can't accidentally do arithmetic on the Match object (more common than you might think)

2) The program seems to be failing on a few Match IDs -- `76557` and `74539` seem to be failing for me with the error `ValueError`.

**Comment by dwillis** [comment]
The good news is that you can pass in a string currently and the `Match` constructor just works, so I'll update the docs. The match IDs you referenced don't seem to be valid, but I'm adding a custom error for that. Thanks!
